# Displays when attempting to execute a player-only command through the console.

must-be-player: "&7You must be a player to execute that command."

# These messages are activated by commands.

cmd:

  balance:
    success: "&6You have %AMOUNT% gold in your account."
  
  deposit:
    success: "&6%AMOUNT% gold has been deposited into your account."
    usage: "&7Usage: /deposit <amount>"
    
  withdraw:
    success: "&6%AMOUNT% gold has been withdrawn from your account."
    usage: "&7Usage: /withdraw <amount>"
  
  buy:
    success:
      buyer: "&6Bought %AMOUNT% %MATERIAL% for %TOTAL% gold."
      seller: "&6Someone just bought %AMOUNT% %MATERIAL% from you for %TOTAL% gold!"
    usage: "&7Usage: /buy <amount> <item> <price>"
    
  sell:
    success: "&6Placed %AMOUNT% %MATERIAL% on market for %PRICE% gold each."
    usage: "&7Usage: /sell <amount> <item> <price>"
    fail: "&cYou do not have %AMOUNT% %MATERIAL% in your inventory."
    amount-zero: "&cYou must sell at least one!"
    
  price:
    success: "&6%AMOUNT% %MATERIAL% costs %TOTAL% gold."
    usage: "&7Usage: /price <amount> <item>"

  economy:
    - "&6/economy - Display this message."
    - "&6/balance - Check your account balance."
    - "&6/deposit - Deposit gold into your account."
    - "&6/withdraw - Withdraw gold from your account."
    - "&6/buy - Buy an item from the market."
    - "&6/sell - Place an item on the market."
    
  not-enough-on-market: "&cThere is not %AMOUNT% %MATERIAL% on the market.
  not-enough-money: "&cYou do not have enough gold to do that."
  internal-error: "&4Failed. Internal error."
